# Generated by Django 4.2 on 2023-07-21 00:34

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=' ', editable=False, populate_from='title'),
            preserve_default=False,
        ),
    ]
